# Generated by Django 5.1.3 on 2024-12-10 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('temperature', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('cholestrol', models.FloatField()),
                ('blood_sugar', models.FloatField()),
                ('systolic', models.FloatField()),
                ('diastolic', models.FloatField()),
                ('existing_conditions', models.CharField(max_length=100)),
                ('family_history', models.CharField(max_length=3)),
                ('smoking_status', models.CharField(max_length=7)),
                ('lab_status', models.CharField(max_length=50)),
                ('symptom', models.CharField(max_length=50)),
                ('prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
