# Generated by Django 5.1.3 on 2024-12-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enquiry',
            table='enquiries',
        ),
    ]
