# Generated by Django 5.1.3 on 2024-12-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='doctor', max_length=10),
        ),
    ]
